### ISSUE TITLE
Draws stale lines

### ISSUE THREAD

**Issue by atbentley** [Toqozz/bevy_debug_lines#1]
Hello, looks like there is a small issue with drawing 'stale' lines.

If on frame one, three calls are made to `DebugLines.lines()`, then three lines are correctly drawn. Then frame two, one call is made to `DebugLines.lines()`, then two lines are drawn but we only expect one to be drawn.

Here's a small demonstration:

```rust
use bevy::prelude::*;
use bevy_prototype_debug_lines::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_plugin(DebugLinesPlugin)
        .add_startup_system(setup.system())
        .add_system(demo.system())
        .run();
}

fn setup(mut commands: Commands) {
    let mut camera = OrthographicCameraBundle::new_2d();
    camera.transform = Transform::from_translation(Vec3::new(0.0, 0.0, 5.0));
    commands.spawn_bundle(camera);
}

#[derive(Default)]
struct Counter {
    count: i32,
}

fn demo(mut counter: Local<Counter>, mut lines: ResMut<DebugLines>) {
    if counter.count == 0 {
        lines.line(Vec3::new(-400.0, 200.0, 0.0), Vec3::new(400.0, 200.0, 0.0), 10.0);
        lines.line(Vec3::new(-400.0, 0.0, 0.0), Vec3::new(400.0, 0.0, 0.0), 10.0);
    }
    lines.line(Vec3::new(-400.0, -200.0, 0.0), Vec3::new(400.0, -200.0, 0.0), 10.0);
    counter.count += 1;
}
```

Looking at the shader it looks like the `num_lines` property of the shader is read, but nothing is being done with it. Is that correct?

https://github.com/Toqozz/bevy_debug_lines/blob/master/src/line.vert#L25

**Comment by Toqozz** [comment]
You're absolutely right, sorry about that.  I've pushed a commit that seems to resolve the issue to master, but haven't been able to test it properly.

Will double check the fix soonish.

**Comment by atbentley** [comment]
I pulled the master branch into my scene and it seems to work ok. Thanks for the quick fix!
