### ISSUE TITLE
shortcut for basic shape

### ISSUE THREAD

**Issue by tguichaoua** [Toqozz/bevy_debug_lines#12]
Could be very useful to have some methods on `DebugLines` to create basics shape like arrow, square, circle ...

**Comment by nicopap** [comment]
Hi, I've considered this, in fact I have a shape library you can snoop your favorites form [the heron debug shape implementation](https://github.com/jcornaz/heron/blob/main/debug/src/shape3d_wireframe.rs). But in the end, the best would be to use [bevy_gizmos](https://github.com/lassade/bevy_gizmos) for most use cases.

**Comment by Toqozz** [comment]
There's some basic shape support thanks to @GarmOfGnipahellir.  Only cuboids/rects right now, but more should be able to be added easily.
