### ISSUE TITLE
Provide a Way to Re-Initialize Debug Lines?

### ISSUE THREAD

**Issue by zicklag** [Toqozz/bevy_debug_lines#25]
I have a use-case where I want to reset my whole world. I do this by deleting all entities other than the Camera. The issue is that it also deletes the debug lines meshes.

I could filter out the debug lines meshes from my query for all entities to delete, but `DebugLinesMesh` is the only defining component, and it's not public.

Alternatively I could delete all entities and have a way to re-initialize debug lines, but the `setup` system is private, too.

**Comment by Toqozz** [comment]
Hmm.  This sounds logical and I'm happy to open up `DebugLinesMesh`, but how do you handle re-initializing the other bevy plugins like `UiPlugin`?  Or maybe none of the other plugins spawn game objects?

**Comment by zicklag** [comment]
So far I haven't seen any other plugins that spawn game objects.

I wonder if you could somehow stick those debug line meshes inside the render world, without sticking them in the game world?

I haven't looked deep enough into it to know, but I know there's like a separate Bevy world used by the render sub-app. I wonder if that could be utilized somehow.

**Comment by Toqozz** [comment]
I've made `DebugLinesMesh` public in `0.8.1`.

I *think* the real solution is supposed to be something with using different worlds, but I'm not really sure and it doesn't seem trivial.  You can use `RenderWorld`, but it's cleared every frame and "only available during the extract stage" so doesn't seem like a good place for our mesh to live.

**Comment by zicklag** [comment]
Sweet, thanks. :+1:

**Comment by zicklag** [comment]
Since I'm just curious about it, I _might_ take a quick look at separate worlds if I get the chance.
