### ISSUE TITLE
Feature Request: Retun handles to all spawned lines.

### ISSUE THREAD

**Issue by alphastrata** [Toqozz/bevy_debug_lines#38]
It'd be nice if we could get the ID of the lines spawned in, and if we could mark them with components.

Imagining a similar usage to those already in bevy's conventions:
```rust
commands.spawn((
        Line {
          start,
          stop,
          duration,
        },
        SomeMarkerStruct, // So we can use the Lines better in queries.
    )).id(); // so we can insta-get it from the ECS at anytime.
}
```
Perhaps similar things could be achieved by exposing more of the Components that `update` uses:
`debug_line_meshes: Query<(&dim::MeshHandle, &DebugLinesMesh)>` could maybe be cool.

I think this would be cool for multiple reasons, including (some of which aren't even what I want to use it for):
- spawn a line relative to some parent geometry i.e to maybe raycast check lines of sight for AI agents etc in games.
- Be able to control specific debug overlay systems in a way that's related to the game objects to which you want to attach them to.
- Be able to toggle on/off specific lines/groups of lines
- Be able to programmatically/conditionally update line geometry/colour on a more granular basis.

Took a look, it's probably a little beyond my comfort zone to implement myself but would love to collab if anyone who thinks this'd be easy for them wants to.

**Comment by Toqozz** [comment]
Would you be able to elaborate a bit more on the use case?  The API is immediate-mode, so when you spawn a line, it only shows up for 1 frame (unless duration is > 0) -- you don't "move" lines.

I can see that this might be useful, but not sure how.  Maybe a more concrete example?

The `DebugLinesMesh` marker component is public, so you *should* be able to grab the mesh using it already, unless I'm missing something?

**Comment by alphastrata** [comment]
> Would you be able to elaborate a bit more on the use case? The API is immediate-mode, so when you spawn a line, it only shows up for 1 frame (unless duration is > 0) -- you don't "move" lines.
> 
> I can see that this might be useful, but not sure how. Maybe a more concrete example?
> 
> The `DebugLinesMesh` marker component is public, so you _should_ be able to grab the mesh using it already, unless I'm missing something?

wow yeah `DebugLinesMesh` would totally work.
#egg on face.

The main reasoning behind the wanting to spawn the Lines via the `cmd.spawn()` pattern was to make them easily parented/parent-able to say a character, as it'd be a useful feature for getting an idea of NPCs' line of sight etc.

In hindsight it's probably trying too hard to massage these into something they may not be for.

**Comment by Toqozz** [comment]
Yeah ok, so the way you'd do something like that is just by having a system that takes the character and the debug lines component, calculates the line of sight in world space, and draws it every frame.

I can see how you might "get it for free" if lines were physical things with transforms and stuff.  But also, you could add some transforms to the character and just use those to draw lines too!

Hopefully that makes sense and is helpful.  Closing!
