### ISSUE TITLE
`Circle` and `Sphere` shapes are missing in crate

### ISSUE THREAD

**Issue by hxYuki** [Toqozz/bevy_debug_lines#39]
![image](https://github.com/Toqozz/bevy_debug_lines/assets/15306248/2425c150-5a99-4731-9c79-2e5961647275)

**Comment by Toqozz** [comment]
Sorry, I haven't done a new crate release yet.  I'll try get around to it soon.

**Comment by Toqozz** [comment]
Should be there now in 0.10.2.
