### ISSUE TITLE
0.5.0 compat

### ISSUE THREAD

**Issue by szunami** [Toqozz/bevy_debug_lines#5]
I am using this plugin in a project, and attempting to upgrade that project to bevy 0.5.0. It looks like the definition of a plugin has changed. I am happy to spend the time to submit a fix, if that is welcome :)

**Comment by Toqozz** [comment]
Hey, this crate (from version 0.3.0 onwards) actually is 0.5 compatible.  I'm using it with 0.5 now!  Would you be able to produce an example of what doesn't work?

https://github.com/Toqozz/bevy_debug_lines/blob/fd43df58d00b7f57b9d0b0632a1e4df31dad77cc/Cargo.toml#L20

**Comment by szunami** [comment]
Ah you are completely right, I should have looked for a new version. I think I am seeing a problem with the new version; I will file a separate issue after I've investigated a bit.

**Comment by Toqozz** [comment]
Please do, thank you.

**Comment by szunami** [comment]
Ah the other issue was due to the new duration paramater. I have updated my code and now everything works as expected. Thanks for everything!

**Comment by Toqozz** [comment]
Cool!  Sorry about the breaking change!
