### ISSUE TITLE
Allow lines to intersect with meshes

### ISSUE THREAD

**Issue by Temak1** [Toqozz/bevy_debug_lines#6]
By default debug lines draws on top on everything. Is it possible to change them to intersect other meshes like any model do?

**Comment by Toqozz** [comment]
Thanks for the issue!

You should be able to configure this now in `0.3.2`:

```rust
use bevy::prelude::*;
use bevy_prototype_debug_lines::*;

fn main() {
    App::build()
    .add_plugins(DefaultPlugins)
    .add_plugin(DebugLinesPlugin)
    .insert_resource(DebugLines { depth_test: true, ..Default::default() })
    ...
    .run();
}
```

![image](https://user-images.githubusercontent.com/6947819/126938724-150bf6da-f026-44b2-b0dd-ab20773f50cd.png)
